services:
  app:
    image: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      INTERNAL_SECRET: mbK5wBePiPEpBBES

      BETTER_AUTH_SECRET: voZW7ZzYqt1JWmGq
      BETTER_AUTH_URL: https://gunex.ca

      DATABASE_URL: postgresql://postgres:postgres@db:5432/appdb

      TYPESENSE_API_KEY: XNggQlHChW0fawET
      TYPESENSE_HOST: typesense
      TYPESENSE_PORT: "8108"
      TYPESENSE_PROTOCOL: http

      AWS_ACCESS_KEY_ID: 4c6ec90389ea3b2aed173d08df7e4072
      AWS_SECRET_ACCESS_KEY: 8cbc6c261effa4ee4db297898cd7e0d54533904e84ea12afc5aa40198b314934
      S3_ENDPOINT: https://25844977d6037335b3c892d222f54af2.r2.cloudflarestorage.com
      S3_PUBLIC_URL_BASE: https://media.gunex.ca

      LISTING_IMAGES_BUCKET: gunex-listings

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2g

  typesense:
    image: typesense/typesense:29.0
    environment:
      - TYPESENSE_API_KEY=XNggQlHChW0fawET
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    expose:
      - "8108"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g

  gunpost-scapper:
    image: gunpost-scapper
    build:
      context: scrapers
      dockerfile: Dockerfile
    environment:
      GUNEX_URL: https://gunex.ca

volumes:
  db_data:
  typesense_data:
