services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gunex
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2g

  typesensedb:
    image: typesense/typesense:29.0
    environment:
      - TYPESENSE_API_KEY=secret
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    ports:
      - "8108:8108"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g

volumes:
  db_data:
  opensearch_data:
  typesense_data:
