services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gunex
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2g

  typesense:
    image: typesense/typesense:29.0
    environment:
      - TYPESENSE_API_KEY=secret
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    ports:
      - "8108:8108"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: always

volumes:
  db_data:
  opensearch_data:
  typesense_data:
  minio_data:
